### ISSUE TITLE
Failure when pulling due to docker compose naming

### ISSUE THREAD

**Issue by rcdailey** [hotio/pullio#1]
If I do not explicitly set `container_name` to the same name as the service in the YAML config, pulls will fail. Take this `docker-compose.yml` as an example:

```yml
version: "3.7"

services:
  db:
    image: mysql:8.0.15

  redis:
    image: redis

  app:
    image: nextcloud:20-apache
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=https://discord.com/api/webhooks/SNIP"

  cron:
    image: ...
```

I also modified line `145` in `pullio.sh` to not silence the errors after running the pull. Running `pullio` gives me this:

```
nextcloud_app_1: Checking...
nextcloud_app_1: Pulling image...
ERROR: No such service: nextcloud_app_1
nextcloud_app_1: Pulling failed!
nextcloud_cron_1: Checking...
nextcloud_db_1: Checking...
nextcloud_redis_1: Checking...
```

The correct command should be `docker-compose pull app`, but it is instead doing `docker-compose pull nextcloud_app_1`, which isn't working. I am not familiar with the implementation, but it seems like you are doing `docker ps` instead of `docker-compose ps` to get the container names. You need the service names, not the container names.
